#! /bin/sh
# . /etc/rc.d/init.d/functions  # uncomment/modify for your killproc
case "$1" in
	start)
        	echo "Starting medimail-webmail"
       		cd /opt/medimail/webmail
		script/server -d
            ;;
        stop)
		echo "Unimplemented"
            ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
        esac
exit 0
