development:
  adapter: mysql
  database: medimail_web_development
  host: localhost
  username: root
#  password: 

test:
  adapter: mysql
  database: mailr_tests
  host: localhost
  username: root
  password: 

production:
  adapter: mysql
  database: mailr
  host: localhost
  username: root
  password: 
