PATIENT_DATA_INDEX_URL = 'druby://localhost:9000'

PATIENT_DISCUSSION_INDEX_URL = 'druby://localhost:9001'
PATIENT_DISCUSSION_INDEX_PERSISTENT_STORE_FILEPATH = "#{MEDIMAIL_ROOT}/data/discussions_index"